# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  
  config.vm.provider "virtualbox" do |vb|
    vb.name = "project6"
    vb.memory = "1024"
    vb.cpus = 1
  end

  config.vm.hostname = "project6"

  config.vm.synced_folder "C:/Users/Anton/Projects/vagrant", "/home/vagrant",
    owner: "www-data", group: "www-data"
  
  config.vm.network "forwarded_port", guest: 80, host: 8000
  config.vm.network "forwarded_port", guest: 3306, host: 33060

  config.vm.network "private_network", ip: "192.168.56.100"

  config.vm.provision "shell", path: "provision.sh"

  config.vm.provision "file", source: "C:/Users/Anton/Projects/vagrant/code.py", destination: "home/vagrant/code.py"
end
